import { currentEvent, matches, notes, robotProjects, teams } from '../data/mockData';
import type { ApiResponse, CodePatch, EventSummary, Match, RobotProject, ScoutingNote, Team } from '../types';

const delay = (ms = 260) => new Promise((resolve) => window.setTimeout(resolve, ms));

export async function apiOk<T>(data: T, meta?: Record<string, unknown>): Promise<ApiResponse<T>> {
  await delay();
  return { ok: true, data, meta };
}

export const robotEventsAdapter = {
  async searchEvents(): Promise<ApiResponse<EventSummary[]>> {
    return apiOk([currentEvent], {
      cacheStatus: currentEvent.status,
      source: 'Mock RobotEvents adapter. Replace server implementation with ROBOTEVENTS_API_TOKEN.',
    });
  },
  async getEventMatches(): Promise<ApiResponse<Match[]>> {
    return apiOk(matches, { refreshSeconds: 60, cacheStatus: 'Fresh' });
  },
  async searchTeams(query = ''): Promise<ApiResponse<Team[]>> {
    const normalized = query.trim().toLowerCase();
    const result = normalized
      ? teams.filter((team) => `${team.number} ${team.name} ${team.tags.join(' ')}`.toLowerCase().includes(normalized))
      : teams;
    return apiOk(result, { normalized: true });
  },
};

export const scoutingService = {
  async listNotes(): Promise<ApiResponse<ScoutingNote[]>> {
    return apiOk(notes, { offlineCapable: true });
  },
  async createNote(note: Omit<ScoutingNote, 'id' | 'updatedAt'>): Promise<ApiResponse<ScoutingNote>> {
    return apiOk({ ...note, id: crypto.randomUUID(), updatedAt: 'now' });
  },
};

export const robotService = {
  async listProjects(): Promise<ApiResponse<RobotProject[]>> {
    return apiOk(robotProjects);
  },
  async simulate(robotId: string): Promise<ApiResponse<{ poses: Array<{ x: number; y: number; heading: number }>; warnings: string[] }>> {
    return apiOk({
      poses: [
        { x: 20, y: 160, heading: 0 },
        { x: 120, y: 160, heading: 0 },
        { x: 180, y: 120, heading: 38 },
        { x: 260, y: 98, heading: 38 },
      ],
      warnings: robotId === 'skills-bot' ? ['Wheel slip not physically calibrated'] : [],
    });
  },
};

export const pathService = {
  async optimizePath(points: Array<{ x: number; y: number }>): Promise<ApiResponse<{ points: Array<{ x: number; y: number }>; patch: CodePatch }>> {
    const safePoints = points.length > 1 ? points : [{ x: 40, y: 270 }, { x: 140, y: 210 }, { x: 270, y: 160 }];
    return apiOk({
      points: safePoints.map((point, index) => ({ x: point.x + index * 4, y: point.y - index * 3 })),
      patch: {
        codeVersionId: 'cv-2026-05-27',
        filePath: 'src/autonomous.cpp',
        insertAfter: { line: 42, pattern: 'void autonomous()' },
        newText: `void autonomousRoute_RoboLab() {
  // Generated by RoboLab from accepted field path
  Drivetrain.setDriveVelocity(55, percent);
  Drivetrain.driveFor(forward, 24, inches);
  Drivetrain.turnFor(right, 38, degrees);
  Drivetrain.driveFor(forward, 18, inches);
}`,
        reason: 'Accepted optimized VEX field path',
        generatedBy: 'path_planner',
      },
    });
  },
};
