// MatchMind i18n — core UI strings in 20 languages.
// Scope: navigation, onboarding, settings, and common actions. Pages fall back to
// English for untranslated strings. AI responses follow the selected language via
// the coach context (see CoachPage/platform context).

export type LangCode =
  | "en" | "es" | "fr" | "de" | "pt" | "it" | "nl" | "pl" | "tr" | "ru"
  | "uk" | "zh" | "ja" | "ko" | "hi" | "ar" | "fa" | "vi" | "id" | "el";

export const LANGUAGES: Array<{ code: LangCode; label: string; native: string }> = [
  { code: "en", label: "English", native: "English" },
  { code: "es", label: "Spanish", native: "Español" },
  { code: "fr", label: "French", native: "Français" },
  { code: "de", label: "German", native: "Deutsch" },
  { code: "pt", label: "Portuguese", native: "Português" },
  { code: "it", label: "Italian", native: "Italiano" },
  { code: "nl", label: "Dutch", native: "Nederlands" },
  { code: "pl", label: "Polish", native: "Polski" },
  { code: "tr", label: "Turkish", native: "Türkçe" },
  { code: "ru", label: "Russian", native: "Русский" },
  { code: "uk", label: "Ukrainian", native: "Українська" },
  { code: "zh", label: "Chinese", native: "中文" },
  { code: "ja", label: "Japanese", native: "日本語" },
  { code: "ko", label: "Korean", native: "한국어" },
  { code: "hi", label: "Hindi", native: "हिन्दी" },
  { code: "ar", label: "Arabic", native: "العربية" },
  { code: "fa", label: "Persian (Farsi)", native: "فارسی" },
  { code: "vi", label: "Vietnamese", native: "Tiếng Việt" },
  { code: "id", label: "Indonesian", native: "Bahasa Indonesia" },
  { code: "el", label: "Greek", native: "Ελληνικά" },
];

export const LANGUAGE_NAME: Record<LangCode, string> = Object.fromEntries(
  LANGUAGES.map((l) => [l.code, l.label]),
) as Record<LangCode, string>;

type Dict = Record<string, string>;

const en: Dict = {
  home: "Home", lookup: "Lookup", coach: "Coach", scout: "Scout", settings: "Settings",
  next: "Next", back: "Back", skip: "Skip", done: "Done", save: "Save", cancel: "Cancel",
  search: "Search", favorites: "Favorites", team: "Team", teams: "Teams", language: "Language",
  signIn: "Sign in", signOut: "Sign out", guest: "Continue as guest",
  welcomeTitle: "Welcome to MatchMind", yourName: "Your name", chooseRole: "Choose your role",
  student: "Student", parent: "Parent", roleCoach: "Coach",
  chooseLanguage: "Choose your language", selectTeam: "Select your team",
  legalTitle: "Legal agreements", agreeTerms: "I agree to the Terms of Service",
  agreePrivacy: "I have read the Privacy Policy", agreeHandbook: "I agree to the Community Guidelines & Handbook",
  getStarted: "Get started", notifications: "Notifications", matches: "Matches", events: "Events",
  awards: "Awards", rankings: "Rankings", todo: "To-Do", tasks: "Tasks",
};

const translations: Record<LangCode, Dict> = {
  en,
  es: { ...en, home: "Inicio", lookup: "Buscar", coach: "Coach", scout: "Scout", settings: "Ajustes", next: "Siguiente", back: "Atrás", skip: "Omitir", done: "Hecho", save: "Guardar", cancel: "Cancelar", search: "Buscar", favorites: "Favoritos", team: "Equipo", teams: "Equipos", language: "Idioma", signIn: "Iniciar sesión", signOut: "Cerrar sesión", guest: "Continuar como invitado", welcomeTitle: "Bienvenido a MatchMind", yourName: "Tu nombre", chooseRole: "Elige tu rol", student: "Estudiante", parent: "Padre/Madre", roleCoach: "Entrenador", chooseLanguage: "Elige tu idioma", selectTeam: "Selecciona tu equipo", legalTitle: "Acuerdos legales", agreeTerms: "Acepto los Términos de Servicio", agreePrivacy: "He leído la Política de Privacidad", agreeHandbook: "Acepto las Normas de la Comunidad", getStarted: "Comenzar", notifications: "Notificaciones", matches: "Partidos", events: "Eventos", awards: "Premios", rankings: "Clasificación", todo: "Tareas", tasks: "Tareas" },
  fr: { ...en, home: "Accueil", lookup: "Recherche", coach: "Coach", scout: "Scout", settings: "Réglages", next: "Suivant", back: "Retour", skip: "Passer", done: "Terminé", save: "Enregistrer", cancel: "Annuler", search: "Rechercher", favorites: "Favoris", team: "Équipe", teams: "Équipes", language: "Langue", signIn: "Se connecter", signOut: "Se déconnecter", guest: "Continuer en invité", welcomeTitle: "Bienvenue sur MatchMind", yourName: "Votre nom", chooseRole: "Choisissez votre rôle", student: "Élève", parent: "Parent", roleCoach: "Coach", chooseLanguage: "Choisissez votre langue", selectTeam: "Sélectionnez votre équipe", legalTitle: "Accords juridiques", agreeTerms: "J'accepte les Conditions d'utilisation", agreePrivacy: "J'ai lu la Politique de confidentialité", agreeHandbook: "J'accepte les Règles de la communauté", getStarted: "Commencer", notifications: "Notifications", matches: "Matchs", events: "Événements", awards: "Récompenses", rankings: "Classement", todo: "Tâches", tasks: "Tâches" },
  de: { ...en, home: "Start", lookup: "Suche", coach: "Coach", scout: "Scout", settings: "Einstellungen", next: "Weiter", back: "Zurück", skip: "Überspringen", done: "Fertig", save: "Speichern", cancel: "Abbrechen", search: "Suchen", favorites: "Favoriten", team: "Team", teams: "Teams", language: "Sprache", signIn: "Anmelden", signOut: "Abmelden", guest: "Als Gast fortfahren", welcomeTitle: "Willkommen bei MatchMind", yourName: "Dein Name", chooseRole: "Wähle deine Rolle", student: "Schüler", parent: "Elternteil", roleCoach: "Coach", chooseLanguage: "Wähle deine Sprache", selectTeam: "Wähle dein Team", legalTitle: "Rechtliche Vereinbarungen", agreeTerms: "Ich akzeptiere die Nutzungsbedingungen", agreePrivacy: "Ich habe die Datenschutzerklärung gelesen", agreeHandbook: "Ich akzeptiere die Community-Richtlinien", getStarted: "Loslegen", notifications: "Benachrichtigungen", matches: "Matches", events: "Events", awards: "Auszeichnungen", rankings: "Rangliste", todo: "Aufgaben", tasks: "Aufgaben" },
  pt: { ...en, home: "Início", lookup: "Buscar", coach: "Coach", scout: "Scout", settings: "Ajustes", next: "Avançar", back: "Voltar", skip: "Pular", done: "Concluído", save: "Salvar", cancel: "Cancelar", search: "Pesquisar", favorites: "Favoritos", team: "Equipe", teams: "Equipes", language: "Idioma", signIn: "Entrar", signOut: "Sair", guest: "Continuar como convidado", welcomeTitle: "Bem-vindo ao MatchMind", yourName: "Seu nome", chooseRole: "Escolha sua função", student: "Estudante", parent: "Responsável", roleCoach: "Técnico", chooseLanguage: "Escolha seu idioma", selectTeam: "Selecione sua equipe", legalTitle: "Acordos legais", agreeTerms: "Aceito os Termos de Serviço", agreePrivacy: "Li a Política de Privacidade", agreeHandbook: "Aceito as Diretrizes da Comunidade", getStarted: "Começar", notifications: "Notificações", matches: "Partidas", events: "Eventos", awards: "Prêmios", rankings: "Classificação", todo: "Tarefas", tasks: "Tarefas" },
  it: { ...en, home: "Home", lookup: "Cerca", coach: "Coach", scout: "Scout", settings: "Impostazioni", next: "Avanti", back: "Indietro", skip: "Salta", done: "Fatto", save: "Salva", cancel: "Annulla", search: "Cerca", favorites: "Preferiti", team: "Squadra", teams: "Squadre", language: "Lingua", signIn: "Accedi", signOut: "Esci", guest: "Continua come ospite", welcomeTitle: "Benvenuto su MatchMind", yourName: "Il tuo nome", chooseRole: "Scegli il tuo ruolo", student: "Studente", parent: "Genitore", roleCoach: "Coach", chooseLanguage: "Scegli la lingua", selectTeam: "Seleziona la tua squadra", legalTitle: "Accordi legali", agreeTerms: "Accetto i Termini di Servizio", agreePrivacy: "Ho letto l'Informativa sulla privacy", agreeHandbook: "Accetto le Linee guida della community", getStarted: "Inizia", notifications: "Notifiche", matches: "Partite", events: "Eventi", awards: "Premi", rankings: "Classifica", todo: "Attività", tasks: "Attività" },
  nl: { ...en, home: "Home", lookup: "Zoeken", coach: "Coach", scout: "Scout", settings: "Instellingen", next: "Volgende", back: "Terug", skip: "Overslaan", done: "Klaar", save: "Opslaan", cancel: "Annuleren", search: "Zoeken", favorites: "Favorieten", team: "Team", teams: "Teams", language: "Taal", signIn: "Inloggen", signOut: "Uitloggen", guest: "Doorgaan als gast", welcomeTitle: "Welkom bij MatchMind", yourName: "Je naam", chooseRole: "Kies je rol", student: "Leerling", parent: "Ouder", roleCoach: "Coach", chooseLanguage: "Kies je taal", selectTeam: "Selecteer je team", legalTitle: "Juridische overeenkomsten", agreeTerms: "Ik ga akkoord met de Servicevoorwaarden", agreePrivacy: "Ik heb het Privacybeleid gelezen", agreeHandbook: "Ik ga akkoord met de Communityrichtlijnen", getStarted: "Beginnen", notifications: "Meldingen", matches: "Wedstrijden", events: "Evenementen", awards: "Prijzen", rankings: "Ranglijst", todo: "Taken", tasks: "Taken" },
  pl: { ...en, home: "Start", lookup: "Szukaj", coach: "Trener", scout: "Scout", settings: "Ustawienia", next: "Dalej", back: "Wstecz", skip: "Pomiń", done: "Gotowe", save: "Zapisz", cancel: "Anuluj", search: "Szukaj", favorites: "Ulubione", team: "Drużyna", teams: "Drużyny", language: "Język", signIn: "Zaloguj się", signOut: "Wyloguj się", guest: "Kontynuuj jako gość", welcomeTitle: "Witamy w MatchMind", yourName: "Twoje imię", chooseRole: "Wybierz swoją rolę", student: "Uczeń", parent: "Rodzic", roleCoach: "Trener", chooseLanguage: "Wybierz język", selectTeam: "Wybierz swoją drużynę", legalTitle: "Umowy prawne", agreeTerms: "Akceptuję Warunki korzystania", agreePrivacy: "Przeczytałem(-am) Politykę prywatności", agreeHandbook: "Akceptuję Zasady społeczności", getStarted: "Rozpocznij", notifications: "Powiadomienia", matches: "Mecze", events: "Wydarzenia", awards: "Nagrody", rankings: "Ranking", todo: "Zadania", tasks: "Zadania" },
  tr: { ...en, home: "Ana Sayfa", lookup: "Ara", coach: "Koç", scout: "Scout", settings: "Ayarlar", next: "İleri", back: "Geri", skip: "Atla", done: "Bitti", save: "Kaydet", cancel: "İptal", search: "Ara", favorites: "Favoriler", team: "Takım", teams: "Takımlar", language: "Dil", signIn: "Giriş yap", signOut: "Çıkış yap", guest: "Misafir olarak devam et", welcomeTitle: "MatchMind'a hoş geldiniz", yourName: "Adınız", chooseRole: "Rolünüzü seçin", student: "Öğrenci", parent: "Veli", roleCoach: "Koç", chooseLanguage: "Dilinizi seçin", selectTeam: "Takımınızı seçin", legalTitle: "Yasal sözleşmeler", agreeTerms: "Hizmet Şartlarını kabul ediyorum", agreePrivacy: "Gizlilik Politikasını okudum", agreeHandbook: "Topluluk Kurallarını kabul ediyorum", getStarted: "Başla", notifications: "Bildirimler", matches: "Maçlar", events: "Etkinlikler", awards: "Ödüller", rankings: "Sıralama", todo: "Yapılacaklar", tasks: "Görevler" },
  ru: { ...en, home: "Главная", lookup: "Поиск", coach: "Коуч", scout: "Скаут", settings: "Настройки", next: "Далее", back: "Назад", skip: "Пропустить", done: "Готово", save: "Сохранить", cancel: "Отмена", search: "Поиск", favorites: "Избранное", team: "Команда", teams: "Команды", language: "Язык", signIn: "Войти", signOut: "Выйти", guest: "Продолжить как гость", welcomeTitle: "Добро пожаловать в MatchMind", yourName: "Ваше имя", chooseRole: "Выберите роль", student: "Ученик", parent: "Родитель", roleCoach: "Тренер", chooseLanguage: "Выберите язык", selectTeam: "Выберите команду", legalTitle: "Правовые соглашения", agreeTerms: "Я принимаю Условия использования", agreePrivacy: "Я прочитал(а) Политику конфиденциальности", agreeHandbook: "Я принимаю Правила сообщества", getStarted: "Начать", notifications: "Уведомления", matches: "Матчи", events: "События", awards: "Награды", rankings: "Рейтинг", todo: "Задачи", tasks: "Задачи" },
  uk: { ...en, home: "Головна", lookup: "Пошук", coach: "Коуч", scout: "Скаут", settings: "Налаштування", next: "Далі", back: "Назад", skip: "Пропустити", done: "Готово", save: "Зберегти", cancel: "Скасувати", search: "Пошук", favorites: "Обране", team: "Команда", teams: "Команди", language: "Мова", signIn: "Увійти", signOut: "Вийти", guest: "Продовжити як гість", welcomeTitle: "Ласкаво просимо до MatchMind", yourName: "Ваше ім'я", chooseRole: "Оберіть роль", student: "Учень", parent: "Батьки", roleCoach: "Тренер", chooseLanguage: "Оберіть мову", selectTeam: "Оберіть команду", legalTitle: "Правові угоди", agreeTerms: "Я приймаю Умови користування", agreePrivacy: "Я прочитав(ла) Політику конфіденційності", agreeHandbook: "Я приймаю Правила спільноти", getStarted: "Почати", notifications: "Сповіщення", matches: "Матчі", events: "Події", awards: "Нагороди", rankings: "Рейтинг", todo: "Завдання", tasks: "Завдання" },
  zh: { ...en, home: "首页", lookup: "查询", coach: "教练", scout: "侦察", settings: "设置", next: "下一步", back: "返回", skip: "跳过", done: "完成", save: "保存", cancel: "取消", search: "搜索", favorites: "收藏", team: "队伍", teams: "队伍", language: "语言", signIn: "登录", signOut: "退出登录", guest: "以访客身份继续", welcomeTitle: "欢迎使用 MatchMind", yourName: "你的名字", chooseRole: "选择你的角色", student: "学生", parent: "家长", roleCoach: "教练", chooseLanguage: "选择语言", selectTeam: "选择你的队伍", legalTitle: "法律协议", agreeTerms: "我同意服务条款", agreePrivacy: "我已阅读隐私政策", agreeHandbook: "我同意社区准则", getStarted: "开始使用", notifications: "通知", matches: "比赛", events: "赛事", awards: "奖项", rankings: "排名", todo: "待办", tasks: "任务" },
  ja: { ...en, home: "ホーム", lookup: "検索", coach: "コーチ", scout: "スカウト", settings: "設定", next: "次へ", back: "戻る", skip: "スキップ", done: "完了", save: "保存", cancel: "キャンセル", search: "検索", favorites: "お気に入り", team: "チーム", teams: "チーム", language: "言語", signIn: "サインイン", signOut: "サインアウト", guest: "ゲストとして続行", welcomeTitle: "MatchMind へようこそ", yourName: "お名前", chooseRole: "役割を選択", student: "生徒", parent: "保護者", roleCoach: "コーチ", chooseLanguage: "言語を選択", selectTeam: "チームを選択", legalTitle: "法的同意", agreeTerms: "利用規約に同意します", agreePrivacy: "プライバシーポリシーを読みました", agreeHandbook: "コミュニティガイドラインに同意します", getStarted: "はじめる", notifications: "通知", matches: "試合", events: "イベント", awards: "賞", rankings: "ランキング", todo: "ToDo", tasks: "タスク" },
  ko: { ...en, home: "홈", lookup: "검색", coach: "코치", scout: "스카우트", settings: "설정", next: "다음", back: "뒤로", skip: "건너뛰기", done: "완료", save: "저장", cancel: "취소", search: "검색", favorites: "즐겨찾기", team: "팀", teams: "팀", language: "언어", signIn: "로그인", signOut: "로그아웃", guest: "게스트로 계속", welcomeTitle: "MatchMind에 오신 것을 환영합니다", yourName: "이름", chooseRole: "역할 선택", student: "학생", parent: "학부모", roleCoach: "코치", chooseLanguage: "언어 선택", selectTeam: "팀 선택", legalTitle: "법적 동의", agreeTerms: "서비스 약관에 동의합니다", agreePrivacy: "개인정보 처리방침을 읽었습니다", agreeHandbook: "커뮤니티 가이드라인에 동의합니다", getStarted: "시작하기", notifications: "알림", matches: "경기", events: "이벤트", awards: "수상", rankings: "순위", todo: "할 일", tasks: "작업" },
  hi: { ...en, home: "होम", lookup: "खोज", coach: "कोच", scout: "स्काउट", settings: "सेटिंग्स", next: "आगे", back: "वापस", skip: "छोड़ें", done: "हो गया", save: "सहेजें", cancel: "रद्द करें", search: "खोजें", favorites: "पसंदीदा", team: "टीम", teams: "टीमें", language: "भाषा", signIn: "साइन इन", signOut: "साइन आउट", guest: "अतिथि के रूप में जारी रखें", welcomeTitle: "MatchMind में आपका स्वागत है", yourName: "आपका नाम", chooseRole: "अपनी भूमिका चुनें", student: "छात्र", parent: "अभिभावक", roleCoach: "कोच", chooseLanguage: "अपनी भाषा चुनें", selectTeam: "अपनी टीम चुनें", legalTitle: "कानूनी समझौते", agreeTerms: "मैं सेवा की शर्तें स्वीकार करता/करती हूँ", agreePrivacy: "मैंने गोपनीयता नीति पढ़ी है", agreeHandbook: "मैं सामुदायिक दिशानिर्देश स्वीकार करता/करती हूँ", getStarted: "शुरू करें", notifications: "सूचनाएँ", matches: "मैच", events: "इवेंट", awards: "पुरस्कार", rankings: "रैंकिंग", todo: "कार्य", tasks: "कार्य" },
  ar: { ...en, home: "الرئيسية", lookup: "بحث", coach: "المدرب", scout: "الاستطلاع", settings: "الإعدادات", next: "التالي", back: "رجوع", skip: "تخطي", done: "تم", save: "حفظ", cancel: "إلغاء", search: "بحث", favorites: "المفضلة", team: "الفريق", teams: "الفرق", language: "اللغة", signIn: "تسجيل الدخول", signOut: "تسجيل الخروج", guest: "المتابعة كضيف", welcomeTitle: "مرحبًا بك في MatchMind", yourName: "اسمك", chooseRole: "اختر دورك", student: "طالب", parent: "ولي أمر", roleCoach: "مدرب", chooseLanguage: "اختر لغتك", selectTeam: "اختر فريقك", legalTitle: "الاتفاقيات القانونية", agreeTerms: "أوافق على شروط الخدمة", agreePrivacy: "قرأت سياسة الخصوصية", agreeHandbook: "أوافق على إرشادات المجتمع", getStarted: "ابدأ", notifications: "الإشعارات", matches: "المباريات", events: "الفعاليات", awards: "الجوائز", rankings: "الترتيب", todo: "المهام", tasks: "المهام" },
  fa: { ...en, home: "خانه", lookup: "جستجو", coach: "مربی", scout: "دیده‌بان", settings: "تنظیمات", next: "بعدی", back: "بازگشت", skip: "رد شدن", done: "انجام شد", save: "ذخیره", cancel: "لغو", search: "جستجو", favorites: "علاقه‌مندی‌ها", team: "تیم", teams: "تیم‌ها", language: "زبان", signIn: "ورود", signOut: "خروج", guest: "ادامه به عنوان مهمان", welcomeTitle: "به MatchMind خوش آمدید", yourName: "نام شما", chooseRole: "نقش خود را انتخاب کنید", student: "دانش‌آموز", parent: "والدین", roleCoach: "مربی", chooseLanguage: "زبان خود را انتخاب کنید", selectTeam: "تیم خود را انتخاب کنید", legalTitle: "توافق‌نامه‌های حقوقی", agreeTerms: "شرایط استفاده از خدمات را می‌پذیرم", agreePrivacy: "سیاست حفظ حریم خصوصی را خوانده‌ام", agreeHandbook: "قوانین انجمن را می‌پذیرم", getStarted: "شروع کنید", notifications: "اعلان‌ها", matches: "مسابقات", events: "رویدادها", awards: "جوایز", rankings: "رده‌بندی", todo: "کارها", tasks: "وظایف" },
  vi: { ...en, home: "Trang chủ", lookup: "Tra cứu", coach: "HLV", scout: "Trinh sát", settings: "Cài đặt", next: "Tiếp", back: "Quay lại", skip: "Bỏ qua", done: "Xong", save: "Lưu", cancel: "Hủy", search: "Tìm kiếm", favorites: "Yêu thích", team: "Đội", teams: "Các đội", language: "Ngôn ngữ", signIn: "Đăng nhập", signOut: "Đăng xuất", guest: "Tiếp tục với tư cách khách", welcomeTitle: "Chào mừng đến với MatchMind", yourName: "Tên của bạn", chooseRole: "Chọn vai trò", student: "Học sinh", parent: "Phụ huynh", roleCoach: "Huấn luyện viên", chooseLanguage: "Chọn ngôn ngữ", selectTeam: "Chọn đội của bạn", legalTitle: "Thỏa thuận pháp lý", agreeTerms: "Tôi đồng ý với Điều khoản dịch vụ", agreePrivacy: "Tôi đã đọc Chính sách quyền riêng tư", agreeHandbook: "Tôi đồng ý với Quy tắc cộng đồng", getStarted: "Bắt đầu", notifications: "Thông báo", matches: "Trận đấu", events: "Sự kiện", awards: "Giải thưởng", rankings: "Xếp hạng", todo: "Việc cần làm", tasks: "Nhiệm vụ" },
  id: { ...en, home: "Beranda", lookup: "Cari", coach: "Pelatih", scout: "Scout", settings: "Pengaturan", next: "Lanjut", back: "Kembali", skip: "Lewati", done: "Selesai", save: "Simpan", cancel: "Batal", search: "Cari", favorites: "Favorit", team: "Tim", teams: "Tim", language: "Bahasa", signIn: "Masuk", signOut: "Keluar", guest: "Lanjut sebagai tamu", welcomeTitle: "Selamat datang di MatchMind", yourName: "Nama Anda", chooseRole: "Pilih peran Anda", student: "Siswa", parent: "Orang tua", roleCoach: "Pelatih", chooseLanguage: "Pilih bahasa", selectTeam: "Pilih tim Anda", legalTitle: "Perjanjian hukum", agreeTerms: "Saya menyetujui Ketentuan Layanan", agreePrivacy: "Saya telah membaca Kebijakan Privasi", agreeHandbook: "Saya menyetujui Pedoman Komunitas", getStarted: "Mulai", notifications: "Notifikasi", matches: "Pertandingan", events: "Acara", awards: "Penghargaan", rankings: "Peringkat", todo: "Tugas", tasks: "Tugas" },
  el: { ...en, home: "Αρχική", lookup: "Αναζήτηση", coach: "Προπονητής", scout: "Σκάουτ", settings: "Ρυθμίσεις", next: "Επόμενο", back: "Πίσω", skip: "Παράλειψη", done: "Έγινε", save: "Αποθήκευση", cancel: "Άκυρο", search: "Αναζήτηση", favorites: "Αγαπημένα", team: "Ομάδα", teams: "Ομάδες", language: "Γλώσσα", signIn: "Σύνδεση", signOut: "Αποσύνδεση", guest: "Συνέχεια ως επισκέπτης", welcomeTitle: "Καλώς ήρθατε στο MatchMind", yourName: "Το όνομά σας", chooseRole: "Επιλέξτε ρόλο", student: "Μαθητής", parent: "Γονέας", roleCoach: "Προπονητής", chooseLanguage: "Επιλέξτε γλώσσα", selectTeam: "Επιλέξτε την ομάδα σας", legalTitle: "Νομικές συμφωνίες", agreeTerms: "Αποδέχομαι τους Όρους Χρήσης", agreePrivacy: "Διάβασα την Πολιτική Απορρήτου", agreeHandbook: "Αποδέχομαι τους Κανόνες Κοινότητας", getStarted: "Ξεκινήστε", notifications: "Ειδοποιήσεις", matches: "Αγώνες", events: "Εκδηλώσεις", awards: "Βραβεία", rankings: "Κατάταξη", todo: "Εργασίες", tasks: "Εργασίες" },
};

export function t(lang: string | null | undefined, key: keyof typeof en): string {
  const dict = translations[(lang as LangCode) || "en"] ?? en;
  return dict[key] ?? en[key] ?? String(key);
}
